bit:
  hamming:
  - base_args: ['@metric']
    constructor: Annoy
    disabled: false
    docker_tag: ann-benchmarks-annoy
    module: ann_benchmarks.algorithms.annoy
    name: annoy
    run_groups:
      annoy:
        args: [[100, 200, 400]]
        query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
float:
  any:
  - base_args: ['@metric']
    constructor: Annoy
    disabled: false
    docker_tag: ann-benchmarks-annoy
    module: ann_benchmarks.algorithms.annoy
    name: annoy
    run_groups:
      annoy:
        args: [[100, 200, 400]]
        query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
