float:
  any:
  - base_args: ['@metric']
    constructor: DuckVDB
    disabled: false
    docker_tag: ann-benchmarks-duckvdb
    module: ann_benchmarks.algorithms.duckvdb
    name: duckvdb
    run_groups:
      LSH:
        args:
          method: ['rplsh']
          lsh_hash_distance: [16, 20, 24, 32]
        query_args: [[10]]
#      LINEARSCAN:
#        args:
#          method: [ 'linear-scan' ]
#        query_args: [ [ 20 ] ]
